### PR TITLE
Don't update GRUB on systems that don't have grub2-mkconfig binary

### PR DESCRIPTION
**Pull request by aronowski**
Simply don't update GRUB on systems that don't have grub2-mkconfig binary.

I also took care of distinct /boot/efi/EFI/X directories since now grub2-mkconfig outputs to a symlink.

This should resolve https://github.com/AlmaLinux/almalinux-deploy/issues/128

### CODE REVIEW

**Comment by andrewlukoshko** [comment]
Could you please update your PR based on Shellcheck report?

**Comment by aronowski** [comment]
Naturally! Done.

**Comment by srbala** [comment]
@aronowski can you post some test logs for review/reference

**Comment by aronowski** [comment]
@srbala Yes, here are the logs for both Raspberry Pi and a UEFI x86_64 system.
[m2a-rpi.log](https://github.com/AlmaLinux/almalinux-deploy/files/9638993/m2a-rpi.log)
[m2a-x86_64.log](https://github.com/AlmaLinux/almalinux-deploy/files/9638994/m2a-x86_64.log)

**Pull request merged**
