### PR TITLE
Add Virtuozzo Linux (VZLinux) 8 Support

### PR DESCRIPTION
**Pull request by futureweb**

### CODE REVIEW

**Comment by futureweb** [comment]
checks adjusted

**Comment by futureweb** [comment]
2 VZLinux Machines converted without Problems.
On 1 VZLinux Machine manual adjust of VERSION_ID (/etc/os-release) was needed - as it still reflected 8 even the machine was on 8.5?!

**Comment by andrewlukoshko** [comment]
Thanks. We'll test it soon.

**Comment by sboldyreva** [comment]
Hello!
Running the script on the latest VZLinux OS has the following output:
```
Check root privileges                                                 OK
Check virtuozzo-8.x86_64 is supported                                 OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Please upgrade your OS from 8 to                                      ERROR
    at least 8.4 and try again
```

**Comment by srbala** [comment]
> VZLinux Machine manual adjust of VERSION_ID (/etc/os-release) was needed - as it still reflected 8 even the machine was on 8.5?!

@futureweb script should be able to pass the check without adjusting any files or should have been added as pre processing steps in documentation

I would suggest to Check for CentOS and CentOS Stream, they have some bypass when OS checks does not follow the standard name/id pattern and apply one for VZLinux

**Comment by futureweb** [comment]
@srbala - thx for the info regarding CentOS Version detection - adopted it for VZLinux - now Script is running fine without changes in /etc/os-release ... :-)

Tested on 2 VZLinux installations - all converted without problems.

**Pull request merged**
